version: '3'
services:
  sftp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.sftp
    ports:
      - '8022:8022'
    env_file:
      - .env

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
